#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 <<SQL
CREATE ROLE authentik LOGIN PASSWORD '${AUTHENTIK_POSTGRESQL__PASSWORD}';
CREATE DATABASE authentik OWNER authentik;
REVOKE ALL ON DATABASE authentik FROM PUBLIC;

CREATE ROLE linkwarden LOGIN PASSWORD '${LINKWARDEN_POSTGRESQL__PASSWORD}';
CREATE DATABASE linkwarden OWNER linkwarden;
REVOKE ALL ON DATABASE linkwarden FROM PUBLIC;
SQL
