#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 <<SQL
CREATE ROLE n8n LOGIN PASSWORD '${N8N_POSTGRESQL__PASSWORD}';
CREATE DATABASE n8n OWNER n8n;
REVOKE ALL ON DATABASE n8n FROM PUBLIC;

CREATE ROLE authentik LOGIN PASSWORD '${AUTHENTIK_POSTGRESQL__PASSWORD}';
CREATE DATABASE authentik OWNER authentik;
REVOKE ALL ON DATABASE authentik FROM PUBLIC;

CREATE ROLE linkwarden LOGIN PASSWORD '${LINKWARDEN_POSTGRESQL__PASSWORD}';
CREATE DATABASE linkwarden OWNER linkwarden;
REVOKE ALL ON DATABASE linkwarden FROM PUBLIC;

CREATE ROLE immich LOGIN PASSWORD '${IMMICH_POSTGRESQL__PASSWORD}';
CREATE DATABASE immich OWNER immich;
REVOKE ALL ON DATABASE immich FROM PUBLIC;
\c immich
CREATE EXTENSION IF NOT EXISTS cube;
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS earthdistance;

CREATE ROLE paperless LOGIN PASSWORD '${PAPERLESS_POSTGRESQL__PASSWORD}';
CREATE DATABASE paperless OWNER paperless;
REVOKE ALL ON DATABASE paperless FROM PUBLIC;
SQL
